name: deep-learning
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tensorflow
  - scikit-learn
  - pytorch
  - pytorch-cuda=12.1 # with gpu
  - torchvision
  - torchaudio
  - opencv
  - pycocotools
  - ipykernel
  - laspy # for laserdata
  - pyvista
  - trame # interactive 3d
  - ipywidgets # interactive 3d
  - rasterio
  - git
  - pip
  - pip:
      - git+https://github.com/facebookresearch/segment-anything.git
